"""initial schema

Revision ID: 6bcae615d797
Revises: 
Create Date: 2026-04-16 11:37:40.163856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bcae615d797'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_owners',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_index(op.f('ix_human_owners_email'), 'human_owners', ['email'], unique=True)
    op.create_table('room_contracts',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('deliverable_spec', sa.Text(), nullable=False),
    sa.Column('max_revision_rounds', sa.Integer(), nullable=False),
    sa.Column('timeout_hours', sa.Integer(), nullable=False),
    sa.Column('owner_a_signed', sa.Boolean(), nullable=False),
    sa.Column('owner_b_signed', sa.Boolean(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_table('agents',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('human_owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('reputation_technical', sa.Float(), nullable=True),
    sa.Column('reputation_relational', sa.Float(), nullable=True),
    sa.Column('total_jobs_completed', sa.Integer(), nullable=False),
    sa.Column('total_jobs_disputed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['human_owner_id'], ['human_owners.owner_id'], ),
    sa.PrimaryKeyConstraint('agent_id'),
    sa.UniqueConstraint('public_key')
    )
    op.create_index(op.f('ix_agents_human_owner_id'), 'agents', ['human_owner_id'], unique=False)
    op.create_table('rooms',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('agent_a_id', sa.UUID(), nullable=False),
    sa.Column('agent_b_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'REVISION', 'DISPUTED', 'CLOSED', 'ARCHIVED', name='roomstatus'), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Enum('SUCCESS', 'DISPUTE', 'TIMEOUT', name='roomoutcome'), nullable=True),
    sa.ForeignKeyConstraint(['agent_a_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['agent_b_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['room_contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_rooms_agent_a_id'), 'rooms', ['agent_a_id'], unique=False)
    op.create_index(op.f('ix_rooms_agent_b_id'), 'rooms', ['agent_b_id'], unique=False)
    op.create_table('feedback_relational',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_owner_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_agent_id', sa.UUID(), nullable=False),
    sa.Column('would_hire_again', sa.Boolean(), nullable=False),
    sa.Column('trust_level', sa.Float(), nullable=False),
    sa.Column('coordination_quality', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['reviewer_owner_id'], ['human_owners.owner_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_feedback_relational_reviewed_agent_id'), 'feedback_relational', ['reviewed_agent_id'], unique=False)
    op.create_index(op.f('ix_feedback_relational_room_id'), 'feedback_relational', ['room_id'], unique=False)
    op.create_table('feedback_technical',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_agent_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_agent_id', sa.UUID(), nullable=False),
    sa.Column('spec_compliance', sa.Float(), nullable=False),
    sa.Column('communication_clarity', sa.Float(), nullable=False),
    sa.Column('delivery_speed', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['reviewer_agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_feedback_technical_reviewed_agent_id'), 'feedback_technical', ['reviewed_agent_id'], unique=False)
    op.create_index(op.f('ix_feedback_technical_room_id'), 'feedback_technical', ['room_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('sender_agent_id', sa.UUID(), nullable=False),
    sa.Column('content_natural', sa.Text(), nullable=False),
    sa.Column('content_structured', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('message_type', sa.Enum('TASK', 'DELIVERABLE', 'VERIFICATION', 'REVISION_REQUEST', 'SYSTEM', name='messagetype'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.ForeignKeyConstraint(['sender_agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_room_id'), 'messages', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_room_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_feedback_technical_room_id'), table_name='feedback_technical')
    op.drop_index(op.f('ix_feedback_technical_reviewed_agent_id'), table_name='feedback_technical')
    op.drop_table('feedback_technical')
    op.drop_index(op.f('ix_feedback_relational_room_id'), table_name='feedback_relational')
    op.drop_index(op.f('ix_feedback_relational_reviewed_agent_id'), table_name='feedback_relational')
    op.drop_table('feedback_relational')
    op.drop_index(op.f('ix_rooms_agent_b_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_agent_a_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_agents_human_owner_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('room_contracts')
    op.drop_index(op.f('ix_human_owners_email'), table_name='human_owners')
    op.drop_table('human_owners')
    # ### end Alembic commands ###
